---
# This is used in varnish_reload_vcl.j2 to eliminate rhel 6 / 7 dedicated copy of template
- name: set fact varnish_params_dest
  set_fact: varnish_params_dest=/etc/sysconfig/varnish-{{ varnish_instance.name }}

- name: configure varnish-{{ varnish_instance.name }} service
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: sysconfig/varnish.j2
      dest: /etc/sysconfig/varnish-{{ varnish_instance.name }}
      mode: "0644"
    - src: init.d/varnish.j2
      dest: /etc/init.d/varnish-{{ varnish_instance.name }}
      mode: "0755"
    - src: varnish_reload_vcl.j2
      dest: /usr/sbin/varnish_reload_vcl-{{ varnish_instance.name }}
      mode: "0755"
    - src: "{{ varnish_vcl_src_file }}"
      dest: "{{ varnish_vcl_conf }}"
      mode: "0755"
  register: varnish_config
  notify: restart varnish
