---
# This is used in varnish_reload_vcl.j2 to eliminate rhel 6 / 7 dedicated copy of template
- name: set fact varnish_params_dest
  set_fact: varnish_params_dest=/etc/varnish/varnish{{ varnish_service_suffix }}.params

- name: configure varnish{{ varnish_service_suffix }} service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: varnish.params.j2
      dest: "{{ varnish_params_dest }}"
      mode: "0644"
    - src: varnish.service.j2
      dest: /etc/systemd/system/varnish{{ varnish_service_suffix }}.service
      mode: "0644"
    - src: varnish_reload_vcl.j2
      dest: /usr/sbin/varnish_reload_vcl{{ varnish_service_suffix }}
      mode: "0755"
    - src: "{{ varnish_vcl_template }}"
      dest: /etc/varnish/{{ varnish_service_vcl }}.vcl
      mode: "0755"
  register: varnish_config
  notify:
    - reload systemd configuration
    - restart varnish
