---
- name: install varnish-4.1 rpm
  yum:
    name: https://repo.varnish-cache.org/redhat/varnish-4.1.el{{ ansible_distribution_major_version }}.rpm
    state: present

- name: install varnish
  yum: name=varnish state=present

- include: facts.yml

- include: configure-el6.yml
  when: ansible_distribution_major_version == "6"

- include: configure-el7.yml
  when: ansible_distribution_major_version == "7"

- name: start varnish{{ varnish_config_suffix }} service
  service: name=varnish{{ varnish_config_suffix }} state=started enabled=yes
